settings:
  docker:
    parent_image: 537124932651.dkr.ecr.eu-central-1.amazonaws.com/zenml-aptntx:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  # Data ETL & Feature engineering pipelines parameters
  author_names:
    - user_full_name:
        - olawale_formal
    - user_full_name:
        - olawale_papers

  # Generate instruct dataset pipeline parameters
  test_split_size: 0.1
  push_to_huggingface: false
  dataset_id: olawaleibrahim/professionaldocuments
  mock: false
