settings:
  docker:
    parent_image: 53712sdf4932651.dkr.ecr.eu-central-1.amazonaws.com/zenml-yhzpgr:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  user_full_name:
    - olawale_papers
    - olawale_formal
